## ----------------------------------------------------------------------------
## nexus | SingleParticle.mac
##
## Ancillary macro to define the parameters of the single particle generator.
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

/Generator/SingleParticle/particle gamma
/Generator/SingleParticle/min_energy 2.358 MeV
/Generator/SingleParticle/max_energy 2.758 MeV
/Generator/SingleParticle/region CHAMBER