## ----------------------------------------------------------------------------
## nexus | nexus_example1.config.mac
##
## Configuration macro to simulate individual particles
## in a sphere of xenon.
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

/run/verbose 1
/event/verbose 0
/tracking/verbose 0

/process/em/verbose 0

/nexus/random_seed -1


/Geometry/CylindricChamber/targetmaterial LKr
/Geometry/CylindricChamber/pressure 1 bar
/Geometry/CylindricChamber/step_max 1 mm #in millimeters

/Generator/DoublePositronPair/region ACTIVE

/control/execute macros/generators/DoublePositronPair.mac

/control/execute macros/physics/IonizationElectron.mac

/nexus/persistency/safename true
/nexus/persistency/output_file output/2nubpbpLKr_50000.nexus
