## ----------------------------------------------------------------------------
## nexus | CylindricChamber_bb0nu.config.mac
##
## Configuration macro to simulate bb0nu decays in a generic geometry of a GXe or LXe cylinder enclosed in a vessel.
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

/run/verbose 0
/event/verbose 0
/tracking/verbose 0

/process/em/verbose 0

/nexus/random_seed -1

#/Geometry/CylindricChamber/targetmaterial LXe

/Geometry/CylindricChamber/targetmaterial GXe
/Geometry/CylindricChamber/pressure 15 bar
/Geometry/CylindricChamber/step_max 0.2 mm #in millimeters

/Generator/SingleParticle/particle gamma
/Generator/SingleParticle/min_energy 2.203 MeV
/Generator/SingleParticle/max_energy 2.204 MeV
/Generator/SingleParticle/region CHAMBER

#/Generator/IonGenerator/atomic_number 83
#/Generator/IonGenerator/mass_number 214
#/Generator/IonGenerator/region CHAMBER

/control/execute macros/physics/DefaultPhysicsList.mac

/Actions/DefaultEventAction/min_energy 1000 keV
/Actions/DefaultEventAction/max_energy 2850 keV
#/Actions/SingleDecaySteppingAction/DefineSingle 214 83

/nexus/persistency/output_file output/GXe_2204keV_15bar_200mum_step_100000.next
