## ----------------------------------------------------------------------------
## nexus | CylindricChamber_bb0nu.config.mac
##
## Configuration macro to simulate bb0nu decays in a generic geometry of a GXe or LXe cylinder enclosed in a vessel.
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

/run/verbose 0
/event/verbose 0
/tracking/verbose 0

/process/em/verbose 0

/nexus/random_seed 463689

#/Geometry/CylindricChamber/targetmaterial LXe

/Geometry/CylindricChamber/targetmaterial GXe
/Geometry/CylindricChamber/pressure 30 bar
/Geometry/CylindricChamber/step_max 0.1 mm #in millimeters

# use C++ translation of DECAY0
/Generator/Decay0Interface/inputFile none
# for 0 neutrino  bb to Barium Ground state.
#/Generator/Decay0Interface/Xe136DecayMode 1
# for 2 neutrino  bb to Barium Ground state.

/Generator/Decay0Interface/Xe136DecayMode 1
/Generator/Decay0Interface/Ba136FinalState 0
/Generator/Decay0Interface/EnergyThreshold 1 keV


/Generator/Decay0Interface/region ACTIVE

/control/execute macros/physics/IonizationElectron.mac

/Actions/DefaultEventAction/min_energy 2100 keV
/Actions/DefaultEventAction/max_energy 2500 keV

/nexus/persistency/output_file 0nubb/GXe_0nubb_30bar_100mum_step_p3.next